[Environment]
DISPLAY
NO_AT_BRIDGE
XDG_RUNTIME_DIR
OPENCLAW_START
HERMES_START
OPENAI_V1_PROVIDER
OPENAI_V1_URL
OPENAI_V1_PORT
OPENAI_V1_API_KEY_ALIAS
OPENCLAW_OPENAI_V1_DEFAULT_LLM
HERMES_OPENAI_V1_DEFAULT_LLM
HERMES_DASHBOARD_BASIC_AUTH_USERNAME
OPENCLAW_TELEGRAM_CHAT_ID
CALENDAR_URL
CALENDAR_USER
CLOUDFLARE_EMAIL
JUGO_DB_BACKEND
JUGO_DB_HOST
JUGO_DB_PORT
JUGO_DB_NAME
JUGO_DB_USER
JUGO_DB_PREFIX
KACHELMANN_DB_BACKEND
KACHELMANN_DB_URL
KACHELMANN_DB_PORT
KACHELMANN_DB_NAME
KACHELMANN_DB_USER
KACHELMANN_DB_PREFIX
NAPOLEON_DB_BACKEND
NAPOLEON_DB_HOST
NAPOLEON_DB_PORT
NAPOLEON_DB_NAME
NAPOLEON_DB_USER
NAPOLEON_DB_PREFIX
NATURALGROUNDING_DB_BACKEND
NATURALGROUNDING_DB_PREFIX
NATURALGROUNDING_DB_NAME
NATURALGROUNDING_DB_USER
NATURALGROUNDING_DB_URL
NATURALGROUNDING_DB_PORT
NATURALGROUNDING_ADMIN_EMAIL
PV_DACH_DB_BACKEND
PV_DACH_DB_HOST
PV_DACH_DB_PORT
PV_DACH_DB_NAME
PV_DACH_DB_USER
PV_DACH_DB_PREFIX
SPANKER_DB_BACKEND
SPANKER_DB_NAME
SPANKER_DB_USER
SPANKER_DB_URL
SPANKER_DB_PORT
SPANKER_DB_PREFIX
ZEROINBOX_PROVIDER
ZEROINBOX_EMAIL
ZEROINBOX_OPENAI_V1_DEFAULT_LLM

[Configuration]
CITADEL_CLOUDFLARE
CONTAINER_NAME
CODEX_AUTH_PERSISTENCE
OPENCLAW_WORKSPACE_PERSISTENT
HERMES_PERSISTENT
BIP39_PORT
OPENCLAW_GATEWAY_PORT
OPENCLAW_CRONTAB
SAFRANO9999_FULLRUN_ON_START
HERMES_DASHBOARD_PORT
HERMES_API_SERVER_PORT
FLATNOTES_PATH
FLATNOTES_PORT
FASTAPI_HOST
CITADEL_WEBUI_PORT
CITADEL_SUBNET_IP
CITADEL_TAILSCALE
CITADEL_CLOUDFLARE_DOMAIN
CITADEL_CLOUDFLARE_ACCOUNT_ID
CITADEL_CLOUDFLARE_ZONE_ID
CITADEL_CLOUDFLARE_TUNNEL_ID
CITADEL_CLOUDFLARE_ORIGIN_HOST
CODEANALYST_PORT
JUGO_PORT
USE_TMUX
TMUX_SHELL
JUGO_TMUX_SESSION_PREFIX
KACHELMANN_PORT
KIWIX_BRIDGE_PORT
KIWIX_URL
NAPOLEON_PORT
NAPOLEON_OPENAI_V1_DEFAULT_LLM
NATURALGROUNDING_PORT
NATURALGROUNDING_VIDEOS_DIR
PV_DACH_PORT
PV_DACH_OPENAI_V1_DEFAULT_LLM
PV_DACH_QGIS_WEBHOOK_SERVER_ON
PV_DACH_QGIS_WEBHOOK_SERVER_PORT
PV_DACH_QGIS_WEBHOOK_CLIENT_URL
SPANKER_PORT
VIKUNJA_HOST
VIKUNJA_CONTAINER
ASSIGNEE_USERNAME
TRANSPORT
TARGET
VIKAI_OPENCLAW_LLM
VIKAI_HERMES_LLM
ZEROINBOX_ONLY_UNSEEN
ZEROINBOX_REPORTS_VOLUME
ZEROINBOX_LOGS_VOLUME
ZEROINBOX_MAILDIR_VOLUME

[Container]
CLOUDFLARED_START
BIP39_PUBLISH_PORT
OPENCLAW_GATEWAY_PUBLISH_PORT
HERMES_DASHBOARD_PUBLISH_PORT
HERMES_API_SERVER_PUBLISH_PORT
FLATNOTES_PUBLISH_PORT
FEDORA44_AI_CAPABILITIES
FEDORA44_AI_DEVICES
CITADEL_WEBUI_PUBLISH_PORT
CODEANALYST_PUBLISH_PORT
JUGO_PUBLISH_PORT
KACHELMANN_PUBLISH_PORT
KIWIX_BRIDGE_PUBLISH_PORT
NAPOLEON_PUBLISH_PORT
NATURALGROUNDING_PUBLISH_PORT
PV_DACH_PUBLISH_PORT
PV_DACH_QGIS_WEBHOOK_SERVER_PUBLISH_PORT
SPANKER_PUBLISH_PORT

[Build]
CERTS
ELECTRUM_VERSION
LND_VERSION
GETH_VERSION
GETH_COMMIT
WEBHOOK_VERSION
FEDORA44_AI_PORT_RANGE
