[Service]
PassEnvironment=OPENAI_V1_PROVIDER OPENAI_V1_URL OPENAI_V1_PORT OPENAI_V1_KEY OPENCLAW_OPENAI_V1_DEFAULT_LLM BRAVE_API_KEY VIKUNJA_HOST VIKUNJA_URL TOKEN_WORKER TOKEN_ARCHITECT TOKEN_QC
ExecCondition=/bin/bash -c '[ -n "$$OPENAI_V1_KEY" ] && [ -n "$$OPENAI_V1_URL" ] && [ -n "$$OPENAI_V1_PORT" ]'
